/**
 * TestManagement Studio Backend API
 * <<Some text >>   Would respond with: ```js callbackFunction({     ... }); ``` 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Anyone who can does actions. (Users & Groups)
 */
export interface Actor extends models.SecuredEntity {
    roles?: Array<models.Role>;

    /**
     * Tests to to be completed, assigned to the actor
     */
    testSets?: Array<models.TestSet>;

}
