/**
 * TestManagement Studio Backend API
 * <<Some text >>   Would respond with: ```js callbackFunction({     ... }); ``` 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Category extends models.SecuredEntity {
    name?: string;

    parent?: models.Category;

    childrens?: Array<models.Category>;

    questions?: Array<models.Question>;

    tests?: Array<models.Test>;

}
