/**
 * TestManagement Studio Backend API
 * <<Some text >>   Would respond with: ```js callbackFunction({     ... }); ``` 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Group extends models.Actor {
    name?: string;

    /**
     * The group visible for only the creator.
     */
    isPrivate?: boolean;

    creator?: models.User;

    /**
     * Users who are member of this group.
     */
    members?: Array<models.User>;

}
