/**
 * TestManagement Studio Backend API
 * <<Some text >>   Would respond with: ```js callbackFunction({     ... }); ``` 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH }                                         from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class UsersApi {
    protected basePath = 'http://localhost/v1';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1,T2>(objA: T1, objB: T2) {
        for(let key in objB){
            if(objB.hasOwnProperty(key)){
                (objA as any)[key] = (objB as any)[key];
            }
        }
        return <T1&T2>objA;
    }

    /**
     * 
     * Register a new user
     * @param email The users&#39;s email
     * @param password The users&#39;s password
     * @param firstName The users&#39;s firstname
     * @param lastName The users&#39;s lastname
     */
    public addUser(email: string, password: string, firstName?: string, lastName?: string, extraHttpRequestParams?: any): Observable<string> {
        return this.addUserWithHttpInfo(email, password, firstName, lastName, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Delete user
     * This can only be done by the logged in user.
     * @param userId The user identifier number
     */
    public deleteUser(userId: number, extraHttpRequestParams?: any): Observable<{}> {
        return this.deleteUserWithHttpInfo(userId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Get the actual user
     * 
     */
    public getActualUser(extraHttpRequestParams?: any): Observable<models.User> {
        return this.getActualUserWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Get basic information about an user.
     * @param userId The user identifier number
     */
    public getUser(userId: number, extraHttpRequestParams?: any): Observable<models.User> {
        return this.getUserWithHttpInfo(userId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * Get all registered users
     */
    public listUsers(extraHttpRequestParams?: any): Observable<Array<models.User>> {
        return this.listUsersWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Update user
     * This can only be done by the logged in user.
     * @param email The users&#39;s email
     * @param password The users&#39;s password
     * @param firstName The users&#39;s firstname
     * @param lastName The users&#39;s lastname
     */
    public updateActualUser(email: string, password: string, firstName?: string, lastName?: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.updateActualUserWithHttpInfo(email, password, firstName, lastName, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Update a certain user
     * This can only be done by the logged in user.
     * @param userId The user identifier number
     * @param email The users&#39;s email
     * @param password The users&#39;s password
     * @param firstName The users&#39;s firstname
     * @param lastName The users&#39;s lastname
     */
    public updateUser(userId: number, email: string, password: string, firstName?: string, lastName?: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.updateUserWithHttpInfo(userId, email, password, firstName, lastName, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * 
     * Register a new user
     * @param email The users&#39;s email
     * @param password The users&#39;s password
     * @param firstName The users&#39;s firstname
     * @param lastName The users&#39;s lastname
     */
    public addUserWithHttpInfo(email: string, password: string, firstName?: string, lastName?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        let formParams = new URLSearchParams();

        // verify required parameter 'email' is not null or undefined
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling addUser.');
        }
        // verify required parameter 'password' is not null or undefined
        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling addUser.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'multipart/form-data'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            
        headers.set('Content-Type', 'application/x-www-form-urlencoded');


        if (email !== undefined) {
            formParams.set('email', <any>email); 
        }
        if (password !== undefined) {
            formParams.set('password', <any>password); 
        }
        if (firstName !== undefined) {
            formParams.set('firstName', <any>firstName); 
        }
        if (lastName !== undefined) {
            formParams.set('lastName', <any>lastName); 
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Delete user
     * This can only be done by the logged in user.
     * @param userId The user identifier number
     */
    public deleteUserWithHttpInfo(userId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users/${userId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling deleteUser.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded', 
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get the actual user
     * 
     */
    public getActualUserWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users/me`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded', 
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * Get basic information about an user.
     * @param userId The user identifier number
     */
    public getUserWithHttpInfo(userId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users/${userId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling getUser.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded', 
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * Get all registered users
     */
    public listUsersWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded', 
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Update user
     * This can only be done by the logged in user.
     * @param email The users&#39;s email
     * @param password The users&#39;s password
     * @param firstName The users&#39;s firstname
     * @param lastName The users&#39;s lastname
     */
    public updateActualUserWithHttpInfo(email: string, password: string, firstName?: string, lastName?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users/me`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        let formParams = new URLSearchParams();

        // verify required parameter 'email' is not null or undefined
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling updateActualUser.');
        }
        // verify required parameter 'password' is not null or undefined
        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling updateActualUser.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'multipart/form-data'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            
        headers.set('Content-Type', 'application/x-www-form-urlencoded');


        if (email !== undefined) {
            formParams.set('email', <any>email); 
        }
        if (password !== undefined) {
            formParams.set('password', <any>password); 
        }
        if (firstName !== undefined) {
            formParams.set('firstName', <any>firstName); 
        }
        if (lastName !== undefined) {
            formParams.set('lastName', <any>lastName); 
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Update a certain user
     * This can only be done by the logged in user.
     * @param userId The user identifier number
     * @param email The users&#39;s email
     * @param password The users&#39;s password
     * @param firstName The users&#39;s firstname
     * @param lastName The users&#39;s lastname
     */
    public updateUserWithHttpInfo(userId: number, email: string, password: string, firstName?: string, lastName?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users/${userId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        let formParams = new URLSearchParams();

        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling updateUser.');
        }
        // verify required parameter 'email' is not null or undefined
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling updateUser.');
        }
        // verify required parameter 'password' is not null or undefined
        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling updateUser.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'multipart/form-data'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (Bearer) required
        if (this.configuration.apiKey)
        {
            headers.set('Authorization', this.configuration.apiKey);
        }
            
        headers.set('Content-Type', 'application/x-www-form-urlencoded');


        if (email !== undefined) {
            formParams.set('email', <any>email); 
        }
        if (password !== undefined) {
            formParams.set('password', <any>password); 
        }
        if (firstName !== undefined) {
            formParams.set('firstName', <any>firstName); 
        }
        if (lastName !== undefined) {
            formParams.set('lastName', <any>lastName); 
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
