/**
 * TestManagement Studio Backend API
 * <<Some text >>   Would respond with: ```js callbackFunction({     ... }); ``` 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User extends models.Actor {
    nickName?: string;
    
    email?: string;

    password?: string;

    firstName?: string;

    lastName?: string;

    /**
     * Groups which are created by the user
     */
    groups?: Array<models.Group>;

    memberOf?: Array<models.Group>;

    role?: models.Role;

    /**
     * Tests created by the user
     */
    tests?: Array<models.Test>;

    /**
     * Tests are completed by the user
     */
    testExecutions?: Array<models.TestExecution>;

}
